"""Daily Pulse report builder.

Aggregates classified tickets into a concise markdown report for managers:
volume, breakdowns (category / sentiment / routed team / top intents), risks
(escalated tickets), a low-confidence triage queue (human review), an executive
pain-point summary, and sample drafted responses.

Schema: the model predicts category / intent / sentiment; team is routed from
category by the agent. There is no urgency head.
"""
from __future__ import annotations

from collections import Counter
from datetime import datetime


def _dist(rows: list[dict], task: str) -> str:
    counts = Counter(r["prediction"][task]["label"] for r in rows if task in r["prediction"])
    total = sum(counts.values()) or 1
    parts = [f"{label}: {n} ({n / total:.0%})" for label, n in counts.most_common()]
    return " · ".join(parts)


def build_report(processed: list[dict], summary: str, run_date: str | None = None) -> str:
    run_date = run_date or datetime.now().strftime("%Y-%m-%d")
    n = len(processed)

    risks = [p for p in processed if p.get("escalated")]
    triage = [p for p in processed if p["low_confidence"]]

    lines: list[str] = []
    lines.append(f"# InsightFlow — Daily Pulse · {run_date}")
    lines.append("")
    lines.append(f"**Tickets processed:** {n}  |  **Escalated:** {len(risks)}  |  "
                 f"**Needs human triage:** {len(triage)}")
    lines.append("")

    lines.append("## Executive summary")
    lines.append(summary)
    lines.append("")

    lines.append("## Breakdown")
    lines.append(f"- **By category:** {_dist(processed, 'category')}")
    lines.append(f"- **By sentiment:** {_dist(processed, 'sentiment')}")
    lines.append(f"- **By routed team:** {_dist(processed, 'team')}")
    lines.append(f"- **Top intents:** {_top_intents(processed)}")
    lines.append("")

    lines.append("## Risks — escalated tickets")
    lines.append("_Escalated when sentiment is Negative or the category is business-sensitive._")
    if risks:
        for p in risks[:10]:
            pr = p["prediction"]
            lines.append(
                f"- `{p['ticket_id']}` **{pr['sentiment']['label']}** · "
                f"{pr['category']['label']} → {pr['team']['label']} — {p['text'][:120]}"
            )
    else:
        lines.append("- None this batch.")
    lines.append("")

    lines.append("## Human triage queue — low-confidence predictions")
    if triage:
        lines.append("_Below the confidence threshold (category/sentiment) — route to a human before acting._")
        for p in triage[:10]:
            from src.classifier.inference import TicketClassifier
            conf = TicketClassifier.min_confidence(p["prediction"])
            lines.append(f"- `{p['ticket_id']}` (min confidence {conf:.0%}) — {p['text'][:110]}")
    else:
        lines.append("- None — all predictions above threshold.")
    lines.append("")

    lines.append("## Recommended actions")
    for action in _recommended_actions(processed, risks):
        lines.append(f"- {action}")
    lines.append("")

    lines.append("## Sample drafted responses (require review)")
    drafted = [p for p in processed if p.get("draft")][:3]
    if drafted:
        for p in drafted:
            lines.append(f"\n**{p['ticket_id']}** — {p['prediction']['category']['label']}")
            lines.append("")
            lines.append("```")
            lines.append(p["draft"])
            lines.append("```")
    else:
        lines.append("- No drafts generated this batch.")
    lines.append("")

    lines.append("---")
    lines.append("_Generated by InsightFlow Enterprise Pulse Agent. "
                 "All outputs are suggestions and require human review before action._")
    return "\n".join(lines)


def _top_intents(processed: list[dict], k: int = 5) -> str:
    counts = Counter(p["prediction"]["intent"]["label"] for p in processed if "intent" in p["prediction"])
    if not counts:
        return "n/a"
    return " · ".join(f"{lab} ({n})" for lab, n in counts.most_common(k))


def _recommended_actions(processed: list[dict], risks: list[dict]) -> list[str]:
    actions = []
    cat_counts = Counter(p["prediction"]["category"]["label"] for p in processed)
    if cat_counts:
        top_cat, top_n = cat_counts.most_common(1)[0]
        actions.append(f"Top driver is **{top_cat}** ({top_n} tickets) — consider a targeted fix or FAQ update.")
    neg = sum(1 for p in processed if p["prediction"]["sentiment"]["label"] == "Negative")
    if processed and neg / len(processed) > 0.5:
        actions.append("Negative sentiment exceeds 50% — flag to leadership and prioritize response SLAs.")
    if risks:
        actions.append(f"Review **{len(risks)}** escalated ticket(s) and approve drafted responses before sending.")
    if not actions:
        actions.append("Volume and sentiment are within normal range — no escalations needed.")
    return actions
